### ISSUE TITLE
Hapi instead of express

### ISSUE THREAD

**Issue by davidchase** [TopCloud/socketcluster#10]
Hi i know this might be a little outside the scope, but is there a way to use hapi instead of express? it seems like express exposes a method `var app = require('express')();` which i can use in conjunction with the worker `httpServer.on('req', app)` it doesnt seem that hapi.js does the same.

thanks
-David

**Comment by jondubois** [comment]
Note that if you use newer versions of SC you can now use any framework so long as it exposes an HTTP server object (or one that has a compatible API and events).

SC uses the Node.js HTTP or HTTPS module internally by default but you can provide a custom HTTP/HTTPS server module. Search for `httpServerModule` option here: https://socketcluster.io/#!/docs/api-socketcluster

You need to make sure that your module exports a `createServer(protocolOptions)` function which returns a Node.js-compatible HTTP(S) server. At the very least, this server needs to support the following events:

- 'request'
- 'upgrade'
- 'error' (Make sure your custom server emits errors when it fails)

Also your custom HTTP(S) server needs to expose the following methods:

- listen(sourcePort, [host, tcpSynBacklog])
- close([callback])
