### ISSUE TITLE
How to get the remote IP address

### ISSUE THREAD

**Issue by ghost** [TopCloud/socketcluster#14]
I want to be able to retrieve the IP address of an incoming connection.

I tried socket.request.connection.remoteAddress but is not working.

Any idea?

**Comment by zalmoxisus** [comment]
@jondubois, `socket.clientAddress` is not available anymore? It's `null` while `socket.request.headers['x-forwarded-for']` points to the remote IP address.

**Comment by jondubois** [comment]
@zalmoxisus To get the IP of the machine on the other side of the connection, you have to use the ```socket.remoteAddress``` property. Note that if you are running the SC server behind a proxy, the remoteAddress will point to the IP address of your proxy.

If you're running behind a proxy, you won't be able to see the end-client's IP directly and so you should read their address from ```socket.request.headers['x-forwarded-for']``` - It is a convention for most proxies to put the end-client's IP inside the ```x-forwarded-for header``` - It depends on your proxy though but most follow this convention.

**Comment by zalmoxisus** [comment]
Thank you, @jondubois, for the details! `socket.remoteAddress` works for me even behind nginx proxy.

**Comment by zalmoxisus** [comment]
Just to notice that starting from version 5, `socket.remoteAddress` doesn't work anymore, but `socket.request.headers['x-forwarded-for']` does the trick.
