### ISSUE TITLE
tool performance test socketcluster

### ISSUE THREAD

**Issue by nhatduong** [TopCloud/socketcluster#26]
Hello,
I'm building applications based on nodejs, I'm resolving implementation problems handling multiple connections from the client. I've found you "socketcluster", I tried but I can not test yourself socketcluster performance. Please give me one tool that can check the performance of socketcluster on 200k connection.

Sorry for my english.

Thanks !

**Comment by vmosyaykin** [comment]
For anyone who came here from google:
It seems that now you do need to pass a 'force new connection' option, specifically `multiplex: false`.

See here:
https://github.com/SocketCluster/socketcluster-client/blob/master/socketcluster.js#L1171-L1180

**Comment by happilymarrieddad** [comment]
@jondubois What are you saying!!!! Windows is the best platform to run everything on. I'm offended by these allegations!!! =) Ah man, windows is terrible lol.
