### ISSUE TITLE
Store usage example. Push data from php.

### ISSUE THREAD

**Issue by mlmarius** [TopCloud/socketcluster#30]
Hi. I'm just starting to develop my socketcluster based app and i was wondering if there is any way in which i can push data to the socketcluster app from outside. My main app is running on php and from that i would like to send information into socketcluster. Could you outline how to set up such a thing on the socketcluster side ? Is it best to implement this at a store level or somewhere else ?

**Comment by jondubois** [comment]
I'm closing this issue. This problem will be solved by a Redis plugin. See https://github.com/TopCloud/socketcluster/issues/38
