### ISSUE TITLE
SC load monitoring, clients listening

### ISSUE THREAD

**Issue by joinfok** [TopCloud/socketcluster#33]
Hello!

Howto listing, monitoring SC on live?

eg.: listing global clients data as live(ip,sid,ssid,cookie,browser,custom-data) and collate/group as worker, namespace...etc, and monitoring process time, load, memory....etc.

This is good feathure to administrative monitoring main system. I use one very old chatroom server and good plan the admin monitor (listing and parsing clients eg.: error finding, service supporting to clients...etc).

**Comment by mlmarius** [comment]
Hi. So is there any way to get some stats from the socketcluster like count of currently connected clients across the entire cluster ? I've been reading this: http://mosquitto.org/man/mosquitto-8.html and i think it is a good sollution. The thing publishes stats to some system topics and you can just listen there for them.

**Comment by jondubois** [comment]
@mlmarius Yes, I like the idea of having special channels for the system status.

Right now if you wanted to get the client count, you would have to make your own channel and publish the updated client count to it manually (and you also have to keep track of the client count which is extra work).
