### ISSUE TITLE
How To Scale SocketCluster Across Multiple Machines?

### ISSUE THREAD

**Issue by 1manStartup** [TopCloud/socketcluster#36]
Hi there. I'm looking to scale SocketCluster in production across multiple machines horizontally. 
I read your response to another user (https://github.com/TopCloud/socketcluster/issues/12) on the role that NData plays in SC, but am not sure how to scale.

1) Would SocketCluster be scaled the same way socket.io is scaled across multiple machines using redis pub/sub,MessageQueue, HAProxy?

2) Would the 'SocketCluster' cluster object need to be configured in any way for multiple servers, for example I notice the sample code has the following settings:

 balancers: Number(argv.b) || 1,
  workers: Number(argv.w) || 1,
  stores: Number(argv.s) || 1,

 But what would determine the number '1' here? The number of cpu cores on each machine? Or how many servers we are trying to scale horizontally with?

3) Also does SocketCluster still require the built-in node cluster module (http://nodejs.org/api/cluster.html) to be used, to access multiple cpu cores?

Thanks.

**Comment by acoyfellow** [comment]
+1 to the tutorials. Very interested in those.. thanks for the hard work on this

**Comment by jondubois** [comment]
I also got a couple of emails asking for this. The pressure is on :p

The API page for the Store object is almost done - It might be enough to get started (it should give a fairly good idea of how to hook up SC stores to external Pub/Sub systems to achieve scalability across multiple machines). I should be able to put the new API page up on the website tomorrow.

Hopefully the full tutorial soon after that.

**Comment by jondubois** [comment]
I added the API for the store object (http://socketcluster.io/#!/docs/api-store) - Hopefully it's enough to get a basic idea of how to implement horizontal scalability. I will add a tutorial soon for more details.

**Comment by pressla** [comment]
wow, many thanks for the extraordinary work here. It is an amazing architecture!

**Comment by jondubois** [comment]
@pressla Thanks for the feedback :)
I'm going to release a more detailed tutorial soon - But yes the basic idea is that you scale by synchronizing channels between the stores of multiple SC instances/machines.

**Comment by jondubois** [comment]
Here is a guide to scaling SC across multiple machines. It's doesn't go into details of how to setup a distributed message queue, but hopefully it covers the SocketCluster side of things.

Right now I'm collaborating with a startup to introduce an MQTT channel synchronization service to make this a easier. If anyone is interested, feel free to contact me (email is on my GitHub profile).

**Comment by jondubois** [comment]
A Redis adapter has been released. It's not suitable to scale horizontally - Since it only deals with a single server, but it's useful to get an idea of how it all works. Also, it's away to allow third-party systems to interact with internal SC channels.

**Comment by 1manStartup** [comment]
Thanks for your explanation and documentation, really helped me out.

**Comment by 1manStartup** [comment]
Also I noticed that SC allows publishing from client to client. Normally when scaling with pubsub I would go from client->server (MQTT/db)->client. But how would we save a client to client event to db? Or is client to client meant for sending non-persistent messages such as 'User123 is online'?

**Comment by MegaGM** [comment]
I'd also ask @jondubois about client->client emitting. Could you clarify please how it works? Whether any middlewares are effective?

**Comment by 1manStartup** [comment]
@MegaGM the Client API is here(http://socketcluster.io/#!/docs/api-scsocket-client) it works like engine.io-client since that is where it inherits from.

**Comment by 1manStartup** [comment]
@jondubois would client->client be scaled different than client->server->client? I'm currently doing clientA publish while clientB is subscribed. Any data I want to save I would do socket.watch on ClientA, and post to MQ with the onWatch event. So from client (watch event)-> .emit to server (publish on MQTT) -> But then from MQTT onSubscribe?? Would I emit back to ClientB using the Store Object?
http://socketcluster.io/#!/docs/api-store

**Comment by 1manStartup** [comment]
Answering Own Question Here, Hopefully this should help others. So when doing publish/subscribe, I noticed two ways to do it. In the examples below, pub/sub can be used for newsfeeds, chat apps, tickers, or even collaboration apps.
# PubSub-Single Machine (Client->Client)
Lets say there are 2 pages with URLs, /RoomA and /RoomB.
To allow message message to go from RoomA to RoomB do following:
Have RoomB subscribe to RoomA: socket.watch('RoomA') on client
Have RoomA publish to RoomA: socket.publish('RoomA','Hello') on client
The above is enough if you don't need to save the data, (collaboration drawing apps, games, or notifications)
To save data, on either RoomA or RoomB page, inside your socket.watch('RoomA') event you can POST/emit to db, from client.


# PubSub-Multiple Machines(Client->Server->Server)
For Multiple Machines it is more complex. A pubsub system is required (MQTT or Redis).
What I did was have RoomB subscribe and watch to RoomA on client: socket.subscribe('RoomA') and socket.watch('RoomA'), callback inside RoomA. 

And on the RoomA client I do socket.publish('RoomA-PubSub,'Hello'). 'RoomB' does not get this event. Instead I make the 'Store.js' file watch for all publish events:  
//store.js on server

var mqtt = require('mqtt') //Guide Here: http://bazalabs.com/creating-mqtt-application-end-to-end/

client = mqtt.createClient(1883, 'localhost'); //connect to MQTT pubsub 
store.on('publish',function(room,Message){ //room = RoomA, AND, message= Hello 

 client.subscribe(room);
 client.publish(room, Message);//Put message into pubsub 
 client.on('message', function (room, Message) {//when a message is sent
  store.publish(room,Message)//Publishes messages to all clients listening to RoomA, in our case, RoomB.
 });
})

The above publishes to the desired room, without duplicate messages. And can be scaled across multiple machines.  Would like to hear from @jondubois if this is a 'correct' way to scale across multiple machines. Thanks.

**Comment by jondubois** [comment]
@MegaGM - What is mean by client-to-client communication is that one client can publish messages to another client without having to add any special server-side logic to connect the two.

Note that all SC pub/sub messages do go through your SC instance on the backend so you can watch them pass through your MIDDLEWARE_PUBLISH middleware (you can also bock messages or even modify them before they are shared with all other clients).

For example, if you had a channel called 'censored_channel' and a client did this:

```js
// Client code
socket.publish('censored_channel', {message: 'I cannot get this damn thing to work!'});
```

You could have this middleware:

```js
// Server code (worker)
wsServer.addMiddleware(wsServer.MIDDLEWARE_PUBLISH, function (socket, channel, data, next) {
    console.log('PUBLISH', socket.id, channel, data);
    if (channel == 'censored_channel') {
        data.message = data.message.replace(/damn/g, '*****');
    }
    next();
  });
```

That way, all clients would receive the message as:

{message: 'I cannot get this ***** thing to work!'}


@1manStartup - You are on the right track regarding multiple machine scalability. You can also make is so that you receive events from MQTT (that way all SC channels will sync with MQTT ones in realtime).
You should have a look at the sc-redis example here: http://github.com/topcloud/sc-redis
You can listen to 'subscribe' events on store to subscribe to the matching channel the external service.

**Comment by MegaGM** [comment]
Thank you a lot for clarification!
