### ISSUE TITLE
there is java client for android

### ISSUE THREAD

**Issue by wangpeng1** [TopCloud/socketcluster#39]
can  you use it for android using java?

**Comment by jondubois** [comment]
No, not at the moment.

There are platforms like Apache Cordova which can allow you to use JavaScript to make native apps. The SocketCluster client should work with these.

**Comment by hopewise** [comment]
Is there any update?

**Comment by jondubois** [comment]
@hopewise Some community members have been building a native Android client which implements the basic features. I haven't tested it personally though but worth trying: See https://github.com/abpopov/SocketCluster-android-client

**Comment by hopewise** [comment]
Can you please tell me, what do you mean by basic features? and what would be missing?

**Comment by abpopov** [comment]
This client now in dev state. I hope it will be done in two weeks. At this moment you can connect to server, subscribe to channels, and send messages. Some event are not implemented.

**Comment by efkan** [comment]
Hello @abpopov ,

Is there any progress on `SocketCluster-android-client`?
