### ISSUE TITLE
Connection problems with SocketRocket iOS

### ISSUE THREAD

**Issue by victorjussiani** [TopCloud/socketcluster#40]
Hello guys, okay?

I'm doing a iOS app that will communicate by websockets, I'm using SocketCluster as my server and SocketRocket as the client in my application.

I managed to connect to the server and receive data from it, as follows:
```
Connecting to websocket at: Optional(ws://localhost:8000/socketcluster/?transport=websocket)
Websocket connected!!
DidReceiveMessage: 0{"sid":"_w0_8000_0_WvzMBaK_FpjIF4hLAAAG","upgrades":[],"pingInterval":25000,"pingTimeout":60000}
DidReceiveMessage: 4{"event":"connect","data":{"soid":"_w0_8000_0_WvzMBaK_FpjIF4hLAAAG","appName":"app"},"cid":1}

```
However the server does not fire the event: 'connection'.
Could someone help me?

**Comment by jondubois** [comment]
To answer your question as directly as possible:

Off the top of my head, to get the 'connection' event to trigger on the server, you will have to send this JSON immediately after your SocketRocket clients becomes connected

```json
{event: 'ready', cid: 2}
```

The cid is actually a unique id (index) assigned to each message (so you may not want to hard code it like that in production - Your client should count each JSON message and use that as the cid).

As for the bigger picture behind your question:

SocketCluster client has its own (simple JSON) protocol on top of of the engine.io protocol.

It looks like it might be compatible with the SocketRocket client (based on the info you provided), but you might have to create a wrapper class around SocketRocket to expose the same methods as socketcluster-client.

For example, when you call socket.emit('somevent', 'This is a message') on the socketcluster-client, that translates to this JSON string being sent over the WebSocket connection (example):

```json
{event: 'somevent', data: 'This is a message', cid: 2}
```

If you want to do this properly and write your own fully-compatible client on top of SocketRocket, you will have to implement the methods and emit the events described here: http://socketcluster.io/#!/docs/api-scsocket-client

You may want to read the source code for the JavaScript client to try to follow: https://github.com/topcloud/socketcluster-client

The current client does some fancy stuff - For example, it buffers emit() events before actually sending them (that way it handles bad connections better). But you don't need all this fancy stuff to get your client to get it working.

Also, if you do get it working (with your own client wrapper), that would be an awesome open source project. People have asked for native clients for SC before so this would be useful.

**Comment by jondubois** [comment]
@victorjussiani Full-featured SocketCluster native iOS client is ready: https://github.com/topcloud/socketcluster-client-ios
