### ISSUE TITLE
Uncaught exception handler

### ISSUE THREAD

**Issue by maxime-crunding** [TopCloud/socketcluster#41]
Does it exists an uncaught exception handler?

I need one to log what happened in case of fire.

**Comment by jondubois** [comment]
You can listen to the 'error' event on pretty much every object in SC. This includes the client socket, server socket, worker, SCServer, When you listen to the error event on an object, it will prevent errors coming from that object from being uncaught.

To listen to errors on the SocketCluster object, you should listen to the 'fail' event - The fail event could carry any uncaught error from any worker, store or loadbalancer object.

**Comment by maxime-crunding** [comment]
Perfect!
