### ISSUE TITLE
How to get updates from an external (php) application ?

### ISSUE THREAD

**Issue by seme1** [TopCloud/socketcluster#43]
My application is written in php. I experimented with Ratchet (http://socketo.me/) for running a websocket server. However, I am finding SocketCluster much more attractive mainly due to its scalability features. With Ratchet, I used ZeroMQ message for communication between my php application and Ratchet. They have put up a simple guide here http://socketo.me/docs/push on how to do so. It was very simple to achieve.

Is it possible to have a similar implementation with SocketCluster ? What is the best way for communicating between an external app and SocketCluster ?

**Comment by jondubois** [comment]
You can implement an adapter to sync SC channels with external channels from a pub/sub or message queuing service.

There is a partially completed one for Redis:
https://github.com/topcloud/sc-redis

It doesn't let you add password yes, but feel free to modify the source code to get it working for you. Also pull requests are welcome.

At this stage, it's more to show how it works.

**Comment by seme1** [comment]
I am no expert in Redis, but it seems like the SC-Redis plugin require a Redis server to be running. When comparing this to the solution implemented by Ratchet, it looks to me that ZeroMQ is better. 

Wouldn't be possible to have one of the workers (or maybe the store ??) listens to ZeroMQ msgs/channels and work as a relay between external apps and SC? On the other end in Php (or any other language), the developer would push/publish/subscribe to the ZeroMQ worker which in return would simply bypass the received msgs to the real workers (which handle the actual subscriptions and channels)?

The benefit of the above is that there is no need to run a Redis server (and maybe worry about its scalability later on ??). It would be optimal if the loadbalancer in SC can also balance the load of the ZeroMQ worker and launch new instances (or process) when there is a need to do so (just like it does with normal workers).

**Comment by jondubois** [comment]
@seme1 Yes your idea sounds really good. You can also use a third-party message queue 'as a service' and hook up your socketcluster instances to it if you're lazy.

The service would only handle synchronization aspect and you can take care of your own storage/data.
