### ISSUE TITLE
need to have more control over clients reconnect events

### ISSUE THREAD

**Issue by seme1** [TopCloud/socketcluster#45]
In my app, users are authenticated before they are able subscribe to a `private` channel. The sequence for achieving this is be having the client emit("auth",token) upon establishing a connection. Only after the server responds with a `greeting` (after verifying the provided token and tagging the session), users get to subscribe to the `privateChannel` channel.

```javascript
// on the client side:
socket.on('connect', function () {
		socket.emit('auth', {uId: 1412, token: 'secretToken'});
     });

socket.on('greeting', function (data) {
		socket.subscribe("privateChannel");
})
```

The problem I have is when the server goes down or crashes, the client attempts to reconnect and re-subscribes to its old channels. In my app, the authentication sequence gets broken since the socket should only attempt to subscribe to `privateChannel` after receiving the greeting message. 

What's the best way for handling the above problem ? Is there a way to disable auto re-subscribe upon re-connection ? or at least have more control over it ?

**Comment by jondubois** [comment]
When initializing the client, you can use:
```js
var socket = socketCluster.connect({
  // ...
    autoReconnect: false,
  // ...
});
```
^ This option is missing from the Docs ( http://socketcluster.io/#!/docs/api-scsocket-client )... Will fix soon.

Then you can call socket.connect() manually when you're ready to reconnect.
You can listen for 'disconnect' event on the socket.

If autoReconnect is true (default).
You can also specify an object in the connect() method to control how it happens:

```js
autoReconnectOptions: {
  delay: 4000, // fixed delay in milliseconds
  randomness: 1000 // randomness to add on top in milliseconds
}
```

----

There might be other ways to do the same thing without having to re-authenticate (maybe using cookies to store the token on the client and check for that cookie when the client tries to subscribe to a channel <inside SUBSCRIBE middleware>). I will think about this and get back to you.

**Comment by jondubois** [comment]
Authentication is now implemented - It's designed to work seamlessly with the autoReconnect option and also middleware. You can still disable autoReconnect if you like. See website docs: http://socketcluster.io/#!/docs/authentication
