### ISSUE TITLE
Current Plan for SocketCluster V2

### ISSUE THREAD

**Issue by jondubois** [TopCloud/socketcluster#49]
I just thought I should clarify the current plan for SC v2.
If you have any comments or suggestions, feel free to post them here: https://github.com/TopCloud/socketcluster/issues/48

As of now, the idea is that V2 will be almost entirely backwards compatible with v1.
Also **VERY IMPORTANT** to note is that v2 will be optional! Both v1 and v2 will be supported at the same time until WebSockets becomes adopted by more browsers (right now it appears to have about 85% penetration: http://caniuse.com/#search=WebSocket).

The idea is that Developers will be able to seamlessly move their project directly from v1 to v2 without having to change any code (assuming that you don't use the session API). The session API ( http://socketcluster.io/#!/docs/api-session and ) will be marked as deprecated.

The only changes planned right now are these:

- Removing the session object on sockets - If you want to send messages to a user, (across all open tabs for example) you can just send a message to one of their personal channels.
- The BIG one: v2 will use plain WebSockets (no fallback) - The efficiency improvements of using WebSockets is huge - The engine.io long-polling handshake is VERY expensive in a clustered environment like SC.
- Not having to deal with long-polling fallbacks means that we can get rid of load balancer processes entirely (because WebSockets ensure that a user will stay bound to the same worker - We don't have to keep routing EVERY poll request to the correct worker).

The Pros:
- Huge performance gains - I'm hoping for at least a 5x performance improvement over the current version of SC (particularly when it comes to handling new connections). Load balancers currently consume a lot of CPU power so getting rid of them gives a huge speedup.
- Lighter architecture with more focus around pub/sub - Encourages good design.
- SC itself will have simpler source code

The cons (only one I can think of right now - A big one though):
- No WebSocket fallback - You should stick to the current version of SC for a bit longer if you need to support older browsers or proxies (which can be a problem if you don't use SSL - See http://www.infoq.com/articles/Web-Sockets-Proxy-Servers).

**Comment by MegaGM** [comment]
> No WebSocket fallback

Though only ~85% users are able to use websockets, I'm sure it's a good decision. I do not want to interact with clients who still use IE8 at all. Who those people? I cannot even imagine who it is ![](http://smayly.ru/gallery/anime/RedFox/4.gif)

**Comment by jondubois** [comment]
SC v2 will be ready for release in maybe 1 or 2 weeks, but I think it could be a long time before v2 can replace v1 (maybe 1 or more years) - It will depend completely on how users feel about it and also how many users are using v2 compared to v1... Maybe we will have a vote or something.

v2 will be available for those users who don't care about old browsers but v1 will still be the 'main' version...

Examples where v2 might be preferred:

- Online multiplayer games where all your users NEED to have the latest browser to get the best experience possible (for a variety of reasons beside WebSocket support; for example 3D capabilities, need for LocalStorage, etc...).
- Financial trading systems where users won't mind to upgrade browsers (especially if this is an app that they will use on a daily basis as part of their job) :)
- Some types of enterprise apps where users tend to use cutting-edge browsers anyway and upgrading the browser is possible.
- Any other cutting-edge enterprise-oriented application where fast realtime collaboration is critical.

In all other cases, v1 is the right choice!

I'm thinking maybe we shouldn't call it SocketCluster v2 for now... Maybe it should be called SocketCluster VX or SocketCluster WS, ...?
We can then use it as v2 when the time comes.

It's only a matter of time before all frameworks switch to raw WebSockets, I want SC to prepared for the change - I prefer to be 1 year early than 1 month late!

**Comment by pressla** [comment]
This sounds promising.
I have a large number of embedded clients with very limited memory, so the total footprint of the client side is most critical, and secondly the execution overhead should be lowest possible. 
These clients are using nodejs, so compatibility is only an issue for mobile clients for me, and I could live even with seperate systems for each solution.
So plz keep in mind to stay modular and minimalistic on client side. i.e. many cases exist with outgoing traffic only, and this is super simple case which should not require a large libary.
I believe a lean approach is king. most libaries suffer from growing big over time.

**Comment by jondubois** [comment]
@pressla Thanks for your feedback. Yea, V2 is much leaner on both the client and server. I definitely want to keep the client small and lightweight. I think the features which are there now in v2 are pretty much as far as I intend to push - The future will be mostly about optimization. I think any new major features could be made into separate plugins or libraries on top of SC.
