### ISSUE TITLE
Would love to see a socketcluster client sample using nodejs

### ISSUE THREAD

**Issue by pressla** [TopCloud/socketcluster#52]
I am planning to run nodejs scripts on embedded controllers, which propagate realtime data to socketcluster channels. Current samples show in detail how to do that from browser script.

a simple sample what to require and write to channels would do the jump start here.

thanks

**Comment by jondubois** [comment]
You can run the socketcluster-client on node.js on the server too. you just have to:

```js
var scClient = require('socketcluster-client');

// Pass in options object - Same as regular client in browser
var socket = scClient.connect(options);

// Then you can use socket object as you would in the browser
```

**Comment by pressla** [comment]
thanks,

I love socketcluster :)
