### ISSUE TITLE
socket publish and broadcast

### ISSUE THREAD

**Issue by bamoo456** [TopCloud/socketcluster#54]
Hello,

Here is my question description:
If user1 subscribe channel "test", and then publish message to "test", does user1 receive message that he just sent ? If the answer is "YES", can I have any method to make user1 not to receive any data that he just published ?

After read [documents](http://socketcluster.io/#!/docs) and issue #15, it seems that I can not filter data on
Pub/Sub feature.

Thanks for your help :)

btw, socketCluster is really awesome :+1:

**Comment by jondubois** [comment]
Thanks for the feedback.

Yes, all subscribers will receive the message including the publisher (if the publisher is subscribed to the channel). This is a minor efficiency issue in most cases but if it really matters:

One current solution around this is to have named channels for each user which contain the username like 'bob123_test', 'alice3_test', etc... and then on the server, you can use the Global object to subscribe to the generic 'test' channel and watch() for incoming data (let clients publish directly to the 'test' channel) - Then whenever you get new data on that generic 'test' channel on the server, you can re-publish to the appropriate channel of each user who is interested in that channel (excluding the publisher). You will have to include the publisher's username as part of the data to determine who not to publish to - It does mean you will have to do a database/datastore lookup which is less than ideal in some cases.

The current solution is a bit complicated, so I'm thinking of maybe splitting the MIDDLEWARE_PUBLISH line on the server into two: MIDDLEWARE_PUBLISH_IN and MIDDLEWARE_PUBLISH_OUT for filtering both inbound and outbound published messages. Right now the publish line only deals with inbound publish requests so you can filter out inbound messages before they reach the message broker (store) but not on the way out to individual sockets.

I will post here when this feature has been implemented.

**Comment by bamoo456** [comment]
wow, the idea sounds great.
use MIDDLEWARE to filter channel data really useful, it keeps application code more
maintainable :+1: 

truly appreciate your quick response and suggestion here. :)

**Comment by bamoo456** [comment]
Hi, I'm just curious about whether MIDDLEWARE_PUBLISH_OUT will be applied on both sc1 and sc2 when this feature is implemented?

Thanks,

**Comment by jondubois** [comment]
@bamoo456 Yes, it will be applied to both.
It's already out in the latest version of sc2 (v2.1.3).

The changes will be back-ported to v1.3+ - Hopefully by the end of the week.

**Comment by bamoo456** [comment]
useful information, thanks again :)

**Comment by bamoo456** [comment]
Hi @jondubois 
I just saw that `this.MIDDLEWARE_PUBLISH_OUT = 'publishOut'` has been added on `scserver.js`.
However, [documents](http://socketcluster.io/#!/docs) has no related information on it.
Does this feature implemented ? or still under cooking ?
Thanks

**Comment by mailmevenkat** [comment]
@bamoo456 On SC2, this feature is working like a charm but on SC1, i don't know.

**Comment by jondubois** [comment]
@bamoo456 It's on this page: http://socketcluster.io/#!/docs/middleware-and-authorization
But I haven't updated the API pages yet.

This weekend hopefully.

**Comment by jondubois** [comment]
@mailmevenkat Yes it should also work in SC1.

**Comment by bamoo456** [comment]
nice work !  Thanks :+1:

**Comment by bamoo456** [comment]
It's awesome feature and works great.
