### ISSUE TITLE
How To Send Message to A Remote Server using SocketCluster?

### ISSUE THREAD

**Issue by 1manStartup** [TopCloud/socketcluster#56]
Hi. Is there a way to send a socketCluster/websocket message to a remote server also using socketcluster? Similar to REST or the 'Request' library (https://github.com/request/request).

**Comment by 1manStartup** [comment]
This of course can be accomplished with pub/sub from a message queue, but can socketcluster support  server to server (p2p rpc)?

**Comment by jondubois** [comment]
If you need to scale across multiple machines, the best way to allow multiple SC instances to share channels with each other is to hook up your stores (store.js) to a a distributed message queue engine like RabbitMQ or MQTT.

You CAN run the socketcluster-client on Node.js (on the server side) and there are use cases when this might be OK, but if you end up having to maintain a lot of these server-side clients, it can get messy so be careful.
