### ISSUE TITLE
amazon EC2, channel watch on client not working

### ISSUE THREAD

**Issue by killingz0e** [TopCloud/socketcluster#58]
Hi, I have a problem in configuring socketcluster on amazon EC2. I tried both with redis-sc and with the basic socketcluster method.

Locally I have no problem, on the server I can correctly publish data to a channel but the channel.watch on the client is not fired.

Do I miss some configuration?

**Comment by jondubois** [comment]
On EC2, most ports are blocked by default - You need to configure your security group to allow them.

**Comment by killingz0e** [comment]
I have the port 80 on both inbound and outbound setted up, which other ports are needed in case of a channel subscription?

**Comment by jondubois** [comment]
Is your redis server running on a different machine or same machine? If on different machine, it uses port 6379 by default.

Which version of SC are you using?

**Comment by jondubois** [comment]
Try to reinstall SocketCluser - Use the latest version of SC1 v1.3.7 or SC2 v2.1.11. There was an issue with one of the SC1 dependencies not too long ago so that could be the issue.

**Comment by killingz0e** [comment]
Installed the new sc2, opened up all the ports in outbound on ec2, now it
works.

**Comment by delaneyj** [comment]
@killingz0e if it works its probably helpful to close this issue.
