### ISSUE TITLE
Sockets storing and accessing global

### ISSUE THREAD

**Issue by joinfok** [TopCloud/socketcluster#6]
Hello!
I require many minor fethures:

I use socketcluster to multichatroom. Problem, the socket.session is common a many socket in browser (eg.: teil1: i create on room and login moderator and attendee separate tab, common session created. If socket.session.emit is send any. This correct: i send socket.emit. Teil2: I create many room in separate tab, all session is common, tabs/rooms not separated.). Problem: no common labeled store the socket identifying.

Require a external memory store, have accessing all worker to do. this store provide common data to workers/sockets communications. eg.: Client create room, save a key-val into globalStore. Many clients socket id is connect to this (simple object model). If get a new event to socket, find the globalStore all subscribed socket and broadcasting to, or get individual socket and emitting to eg.: private chat.

I try subscribe/unsubscribe undefined now.

I find sessionId customizing, not allowed now.

Or how can identifying simultane all socket and recalling sockat as socket-id?
(Try storing sockets-id in redis and parsing subscribeing, try reloading subscreibed sockets to broadcast...etc)?

Pleas help me creating this feathures!

Regards Balazs

**Comment by efkan** [comment]
It been very useful guide! 
Thanks to all..
