### ISSUE TITLE
Is it time to make SC2 the official version?

### ISSUE THREAD

**Issue by jondubois** [TopCloud/socketcluster#62]
Based on the emails I've been getting and issues raised on GitHub, it seems that most people are using SC2 instead of SC1.

Some developers have had issues where they accidentally installed the wrong client (SC1/SC2 client/server are not cross-compatible) so there is a cost to having SC1 being the main version. Another issue is that right now SC2 is in a branch called socketcluster-v2 (not master) so this makes contributing to SC more difficult since master (SC1) is the default branch.

What I'm proposing to do:
- Move master branch (containing SC1 source) into a new socketcluster-v1 branch
- Move SC1 into a new npm package 'sc1'
- Move SC1 client into new npm package 'sc1-client'
- Replace the current master branch with the socketcluster-v2 branch
- Move SC2 into npm package 'socketcluster' (replacing SC1)
- Move SC2 client into npm package 'socketcluster-client' (replacing SC1 client)
- Put a notice at the top of the GitHub README to let everyone know about the change so they don't unintentionally update from SC1 to SC2.

SC1 will still be available, still backwards compatible with SC2 and will still receive updates, but you will have to be explicit if you want sc1 instead of sc2:
```bash
npm install -g sc1
```
instead of
```bash
// This would install SC2
npm install -g socketcluster
```

Feedback?

**Comment by woubuc** [comment]
Perhaps, upon initialising the Socketcluster server, it could show the version. Then, if a dev misses the announcement and just installs socketcluster thinking they'll get sc1, they could tell from the server log.

In any case, I think moving to sc2 as the main version is a good idea, as long as sc1 doesn't get forgotten/abandoned, since there are definitely still some cases where sc1 would be needed / preferred.

**Comment by tpeace** [comment]
:+1:

**Comment by jondubois** [comment]
@woubuc showing the version number in the console is a good idea!

**Comment by jondubois** [comment]
Done
