### ISSUE TITLE
How do you attach a debugger to the workers?

### ISSUE THREAD

**Issue by delaneyj** [TopCloud/socketcluster#64]
This is just probably a lack of documentation but is there a way to attach a remote debugger [ala Webstorm's](https://www.jetbrains.com/webstorm/help/running-and-debugging-node-js.html) to one/all the workers?  When I try it none of the breakpoints/debugger; hit and my guess is because the extra options `--debug-brk=<port>` aren't getting passed through to the spun up workers node processes and on start there is no further information about worker ports or config.

Any ideas would be appreciated.

**Comment by jondubois** [comment]
The `--debug-brk=<port>` command line is not yet supported, but it's definitely a feature I would like to add. As you suggested, we will have to make sure we pass on the flag to spawned workers.
I will look into this tomorrow.

**Comment by jondubois** [comment]
Feel free to post your findings (or pull request) if you decide to investigate this yourself.

**Comment by jondubois** [comment]
@delaneyj Are you using node-inspector? I will try to get node-inspector working this week.

For my own testing, I have been using node-webkit-agent to check for memory leaks - It doesn't require you to set the --debug-brk flag (it's easy to get working with SC - You just have to require the module in your worker/workers) but it's probably not as feature-rich as node-inspector.

**Comment by delaneyj** [comment]
Sorry, have been moving offices.  So far I had just used webstorm's internal debugger. When you start a node config it sets up the debug-brk and ports and auto continues after first line when launched. Because of the convenience never tried node-inspector until now.  I'm now sure if there is support for node-inspector webstorm support is just a master of configuration.

I know nodemon cascades debug/debug-brk down to the actual node instance.  Perhaps that process could show how to pass info.  Or maybe just have an extra command that sets the debug flag on the first worker, store, etc on different ports.

**Comment by jondubois** [comment]
@delaneyj In the latest releases of socketcluster (both v1 and v2), children now inherit all command line arguments from the master process - So all workers should now receive the --debug or --debug-brk flags.

Not sure how that will play with Webstorm's debugger. Let me know.

**Comment by jondubois** [comment]
... Hmm actually I didn't realize the --debug-brk flag carried a port number with it - I assume this port number will have to be unique for each worker.

Maybe in this case I will need to add a new option like ```debugPorts``` inside server.js where you can define the default debug ports for each worker (based on worker id) and maybe it should log the debug port for each worker on the console when master is launched using the --debug-brk option.

**Comment by delaneyj** [comment]
If I understand it correctoly both debug and debug-brk have ports associated with them with the defaults set to 5858.  A config option would be great,  maybe a starting port defaulted to 5858 that increments per worker?

**Comment by jondubois** [comment]
@delaneyj Yes. The incremental approach might be best and easiest to implement.

**Comment by delaneyj** [comment]
It would be nice to have port initial numbers for the the stores (or any other processes) you are spinning up.

**Comment by delaneyj** [comment]
Finally was able to test this.  Using node-inspector you are able to get to server.js in the example but workers are not accessible.  I'd hope a config/incremental approach per store/server/worker would help this.

**Comment by jondubois** [comment]
@delaneyj @IngwiePhoenix - SocketCluster 2.2.13 (https://www.npmjs.com/package/socketcluster) now supports debugging using node-inspector (https://github.com/node-inspector/node-inspector).

First, make sure that you are using Node.js v0.11.0+ (preferably the latest).

Make sure node-inspector is installed:
```bash
npm install -g node-inspector
```

Then run it in one console window using:
```bash
node-inspector
```
^ You have to keep this one running in its own console (or in the background).


To debug, you need to have a fresh console open. You can now pass a ```--debug-workers``` or ```--debug-stores``` argument when you run your server.js file using node. Make sure you add the new flags **after** the server file name or else it won't work.

E.g.
```bash
node server --debug-workers
```
or
```bash
node server --debug-stores
```

The default debug port for the first worker is 5858, the second worker is 5859, ... (it increments by one) - You should see a debug message get printed to the console telling you which debug ports are open.
You can also provide an different starting port for the first worker:

```bash
node server --debug-workers=5999
```
This applies to stores too:
```bash
node server --debug-stores=5999
```

If you want to debug your master process (server.js), it's the normal
```bash
node --debug-brk server
```
 Note that the order matters in this case too (this time --debug-brk needs to go before the server argument)!

When you're debugging a worker, you may want to make it break on a particular line or else it will go to the end (idle). To do this you need to add a ```debugger;``` statement in your worker.js code where you want it to stop - There is no --debug-brk-worker option (node.js doesn't appear to support this with cluster module) to you have to use ```debugger``` statements if you want it to stop.

Note that if you're in a worker, you will have access to a global ```worker``` object so you can interact with your server and do things like ```worker.global.publish('pong', 'This is a message for pong channel')``` to interact with your clients directly from your worker from inside your debugger. (You don't need to add ```debugger``` statements in your code to access this feature - You can access it from any scope).

When you're debugging a store process, you will have access to a global ```store``` object and you can also interact with the store directly through the debugger.

**Comment by jondubois** [comment]
This will be backported to SC1 this weekend or sometime next week.

**Comment by delaneyj** [comment]
This is awesome, that you for the fast turnaround!

**Comment by IngwiePhoenix** [comment]
@jondubois Awesome news man, very nicely done! This comes in just at the right time as I am beginning to do profiling on my app. Thanks for your awesome work on this! :) #SCRocks
