### ISSUE TITLE
avs-rpc: The error callback gets the return values?!

### ISSUE THREAD

**Issue by IngwiePhoenix** [TopCloud/socketcluster#65]
I just decided, after moving my entire system to use SocketCluster instead of Socket.IO, to see, how many Socket.IO modules actually work. My first try was one that does RPC in a cool way. Turns out...that when using it, I get some really funny behaviour.

In my case, I have a bit of a back-and-forth, in which one events trigger the server to send back registered methods, which are then implemented. Okay, that works. The object is created correctly and just the way I want. BUT then... I call the remote function and the `socket.on("error")` event is triggered. And looking at the object, it turns out that this very object holds the actual return values - wow.

My code:
```javascript
        socket = socketCluster.connect();
        rpc = new avs.ioRpc(socket);
        socket.on('error', function (err) {
            console.log(err);
        });
        socket.on('connect', function () {
            console.log('CONNECTED');
            socket.on("rpc_init_data", function(methods){
                console.log("Methods: "+methods);
                rpcr = rpc.remote.call(rpc, methods);
                console.log(rpcr.foo({baz:"bar"}));
            });
            socket.emit("rpc_init");
        });
```

`rpc_init` triggers `rpc_init_data`, which gets the method names as an array. The remote connection is then created using a "hacky" method. That works fine. But calling `rpcr.foo` does the error.

What could a possible error be?

The module I am using is this: http://npmjs.org/avs-rpc

Yes, I am aware that SocketCluster **is not Socket.IO**. However, they have a very similar client API, which is why I tested this.

Hopefully you can help me on this, because RPC would be awesome to have! :)

Kind regards, Ingwie

**Comment by jondubois** [comment]
@IngwiePhoenix I will investigate more later, but I think it might be related to the way Socket.io and SocketCluster handle 'event responses' differently. That is:

```js
// Client code
socket.emit('myevent', callbackToHandleEventResponse);
```

In SC, the callback is in the form:
```js
callbackToHandleEventResponse(err, data)
```

in Socket.io, it is:
```js
callbackToHandleEventResponse(data)
```

In SC if you pass a callback (optional), it means that the server **has** to explicitly send back something or else it will timeout and pass an err object as the first argument to the callback. In Socket.io - It doesn't timeout and the first argument is just the data.

See http://socketcluster.io/#!/docs/handling-failure
vs
http://socket.io/docs/#sending-and-getting-data-(acknowledgements)

**Comment by IngwiePhoenix** [comment]
Very interesting! I didn't know that there was a difference. I will simply go and fork `avs-rpc` and add SC support, then! :) It has an inheritage mechanism built-in - this should allow me to easily make this one work.

Thanks for your response. =)

**Comment by IngwiePhoenix** [comment]
@gigerlin made it work now. :) Now SC can do events, streams and rpc - which, imho, is amazing!
