### ISSUE TITLE
Passing a proper host variable for the net.listen call

### ISSUE THREAD

**Issue by IngwiePhoenix** [TopCloud/socketcluster#66]
I just pushed my code to my Git repo, which is linked to an actual outsourcing IP, so I can see how things look like on that remote server. So I added `host: some_ip` to my config passed to `new SocketCluster`. Turns out that this does not work. Doing a `grep -r ".listen" node_modules/socketcluster` reveals that only the Port value seems to be used at all.

Is there a way to also enable use of the `host` parameter to `net.listen`? For now I probably have to proxy all connections via Nginx...

**Comment by IngwiePhoenix** [comment]
The initializing part: http://git.ingwie.me/ingwie/bird3/blob/master/node-lib/socketcluster_worker.js
The worker: http://git.ingwie.me/ingwie/bird3/blob/master/node-lib/socketcluster/worker.js

Assume `config.BIRD3.http_port` to be 80 and the `config.BIRD3.host` to be a valid IP.

Then this error pops up:

```
1430952453227 - Origin: Worker (PID 10752)
    [Error] Error: bind EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at cb (net.js:1195:33)
    at shared (cluster.js:586:5)
    at Worker.<anonymous> (cluster.js:561:9)
    at process.<anonymous> (cluster.js:692:8)
    at process.emit (events.js:129:20)
    at handleMessage (child_process.js:324:10)
    at child_process.js:408:7
    at process.handleConversion.net.Native.got (child_process.js:97:7)
    at process.<anonymous> (child_process.js:407:13)
```

So I don't even get to see where the error is caused... all I know is that it must happen before the `module.exports.run` method is called since there is no `.listen` call inside of it.

**Comment by jondubois** [comment]
@IngwiePhoenix EADDRINUSE happens when another process is already using a port. Make sure no other SC instances are running at the same time.

I will check the host issue later today.

**Comment by IngwiePhoenix** [comment]
I checked. There are no other instances of my app. It works on my local Mac, but once deployed to the server, it does not. I suppose it has to do with the host issue.

**Comment by jondubois** [comment]
@IngwiePhoenix There was no way to specify the host in listen() - In the next release, you will be able to specify a host property when you instantiate SC using new SocketCluster({host: 'myhost.com'}).

Are you running the app with the ```--debug``` flag? This could explain the EADDRINUSE.
I'm currently working on improving the debugging experience in SC - Right now it's a bit tricky dealing with multiple processes when debugging - They're all trying to bind to the same port.

I should have this all fixed in the next day or two.

**Comment by IngwiePhoenix** [comment]
I didn't use the NodeJS debugger or anything the like - i just started it up, that's all. :)

Awesome news, I'll take a coding break for that time then, since i need to see my result on the server before i can continue. Good luck on this one! :)

**Comment by jondubois** [comment]
@IngwiePhoenix v2.2.13 should fix the EADDRINUSE issue.

**Comment by IngwiePhoenix** [comment]
Epic. going to try it out immediately.

**Comment by IngwiePhoenix** [comment]
It works! Thanks for this fix :)
