### ISSUE TITLE
Does logLevel settings override default settings?

### ISSUE THREAD

**Issue by fanweixiao** [TopCloud/socketcluster#73]
If setting `loglevel=3` and start koajs project by `DEBUG=* iojs server.js`, there was no log output.

**Comment by jondubois** [comment]
@fanweixiao Yes, that was caused by some old code carried over from SC1 - Like you suggested, it was overwriting the DEBUG env variable which is bad. It has been fixed.

It's been fixed in v2.2.22.
Thanks for reporting!
