### ISSUE TITLE
SC2 - Handling Failure

### ISSUE THREAD

**Issue by orecus** [TopCloud/socketcluster#74]
I've just started playing around with nodeJS and Socketcluster. While testing things out there is one thing that I havn't figured out why it's happening. 

I've copied the example code regarding handling errors but I get an error on my client and the server never gets a response back, I'm sure i'm missing something basic here as I'm new to both nodeJS and SocketCluster.

I get the data to the client properly, but i just can't seem to ack it back to the server that it's recived.

Client:
 ```javascript
        socket.on('server-doGet', function (data, res) {
          if (true) {
            console.log(JSON.parse(data));
            res.end('Success'); // Send back success
          } else {
            res.error('Error message'); // Send back error
          }
        });
```
**Error:** Uncaught TypeError: res.end is not a function

Server Side
```javascript
            socket.emit('server-doGet', JSON.stringify(results), function (err) {
              if (err) { console.log("Error! No response from: "+socket.remoteAddress+' on the emit event: '+err); }
              else { console.log("Success! Successfully emitted response to: "+socket.remoteAddress); }
            });
```
**Error:** Error! No response from: 127.0.0.1 on the emit event: Error: Event response for 'server-doGet' timed out

Any further clarification on how to handle errors would be great!

**Comment by jondubois** [comment]
@orecus The doc was out of date - the API docs were showing the correct (new way) but not in the 'Handling Failures' page. It's been fixed: http://socketcluster.io/#!/docs/handling-failure

**Comment by jondubois** [comment]
@orecus Sorry about for the confusion and thanks for raising this issue.
